#!/bin/bash

echo "Tidy up..."
rm -f build/*

echo "Compile nucleus..."
cp ../common-crosscompiler/cross-16kb.fs cross.fs
cp ../common-crosscompiler/instructionset-16kb-quickstore.fs instructionset.fs
gforth cross.fs instructionset.fs nucleus.fs
rm cross.fs instructionset.fs
echo ""

echo "Compile additional Forth sources..."
cat soft-spi.fs multiboot.fs security.fs ramrom.fs xfer.fs directory.fs transfer.fs > hp71code.fs
# cat soft-spi.fs multiboot.fs > hp71code.fs
cat ../common-forth/coredefinitions.fs basisdefinitions.fs ../common/double.fs ../common/fixpoint.fs ../common-forth/insight-16kb.fs hp71code.fs > included.fs
../common-crosscompiler/icecreammachine-16kb build/nucleus.hex build/iceimage.hex included.fs > build/log.txt

md5sum build/nucleus.hex build/iceimage.hex
